version: "3.9"
services:
  postgres:
    container_name: synapxia-db
    image: postgres:16
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_SCHEMA}
    ports:
      - "5432:5432"
    networks:
      - synapxia-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: synapxia-pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    depends_on:
      - postgres
    networks:
      - synapxia-network

  api:
    container_name: synapxia-api
    build:
      context: ./api
      dockerfile: ./Dockerfile
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./api:/app
    working_dir: /app
    ports:
      - 8000:80
    networks:
      - synapxia-network
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_SCHEMA}
      - APP_ENV=development
      - LOG_LEVEL=debug
      - DB_HOST=${DB_HOST}
      - DB_SCHEMA=${DB_SCHEMA}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - UV_APP=app.main:app
    command: uv run fastapi dev --host 0.0.0.0 --port 80

  ui:
    container_name: synapxia-ui
    build:
      context: ./ui
      dockerfile: ./Dockerfile
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - 4173:4173
    networks:
      - synapxia-network
    environment:
      - NODE_ENV=production
      - API_PATH=http://synapxia-api:8000

networks:
  synapxia-network:
    driver: bridge