-- **********************************
-- ***** Tables Digital Catalog *****
-- **********************************

-- Table categories
CREATE TABLE categories (
    code        VARCHAR(50)  NOT NULL,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    parent      VARCHAR(50),
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ,
    CONSTRAINT pk_categories PRIMARY KEY (code)
);

-- Table features
CREATE TABLE features (
    code        VARCHAR(50)  NOT NULL,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(500),
	type	    VARCHAR(100), -- references List_items where list='CHARS_TYPE'
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ,
    CONSTRAINT pk_features PRIMARY KEY (code)
);

-- Table assets
CREATE TABLE assets (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(500),
	type	    VARCHAR(100)  NOT NULL, -- references List_items where list='ASSET_TYPE'
    category    VARCHAR(50),
    reference   VARCHAR(500),
    status	    VARCHAR(100)  NOT NULL, -- references List_items where list IN ['RESOURCE_STATUS', 'INITIATIVE_STATUS']
	visibility  VARCHAR(100)  NOT NULL, -- references List_items where list='VISIBILITY_LEVEL'
	tags        JSONB,
	detail      TEXT,
    unit        VARCHAR(50),
    team        VARCHAR(50),
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ,
    CONSTRAINT pk_assets PRIMARY KEY (id)
);

-- Table characterizations
CREATE TABLE characterizations (
    asset           BIGINT   NOT NULL,
    feature        VARCHAR(50)   NOT NULL,
    value           VARCHAR(500)  NOT NULL,
    detail          TEXT,
    is_active       BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ,
    CONSTRAINT pk_characterizations PRIMARY KEY (asset, feature)
);

-- Table favorites
CREATE TABLE favorites (
    user_id     BIGINT       NOT NULL,
    asset       BIGINT       NOT NULL,
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ,
    CONSTRAINT pk_favorites PRIMARY KEY (user_id, asset)
);

-- Table actions
CREATE TABLE actions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    asset          BIGINT        NOT NULL,
    user_id        BIGINT        NOT NULL,
	kind	       VARCHAR(100)  NOT NULL, -- references List_items where list='ACTION_KIND'
	type	       VARCHAR(100)  NOT NULL, -- references List_items where list IN ['CONTRIB_TYPE', 'COLLAB_TYPE']
    content        VARCHAR(500),
    reference      VARCHAR(500),
    parent         BIGINT,
	detail         TEXT,
    is_active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ,
    CONSTRAINT pk_actions PRIMARY KEY (id)
);

-- Table asset_relations
CREATE TABLE asset_relations (
    source      BIGINT        NOT NULL,
    target      BIGINT        NOT NULL,
    type        VARCHAR(100)  NOT NULL, -- references List_items where list='ASSET_REL_TYPE'
    rationale   TEXT,
    is_active   BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ,
    CONSTRAINT pk_asset_relations PRIMARY KEY (source, target) 
);

-- ****************************************
-- ************ Foreign Keys **************
-- ****************************************

-- categories.parent → categories.code
ALTER TABLE categories
    ADD CONSTRAINT fk_categories_categories
    FOREIGN KEY (parent)
    REFERENCES categories(code);

-- assets.category → categories.code
ALTER TABLE assets
    ADD CONSTRAINT fk_assets_categories
    FOREIGN KEY (category)
    REFERENCES categories(code);

-- assets.unit → business_units.code
ALTER TABLE assets
    ADD CONSTRAINT fk_assets_business_units
    FOREIGN KEY (unit)
    REFERENCES business_units(code);

-- assets.team → teams.code
ALTER TABLE assets
    ADD CONSTRAINT fk_assets_teams
    FOREIGN KEY (team)
    REFERENCES teams(code);

-- characterizations.asset → assets.id
ALTER TABLE characterizations
    ADD CONSTRAINT fk_charzs_assets
    FOREIGN KEY (asset)
    REFERENCES assets (id);

-- characterizations.feature → features.code
ALTER TABLE characterizations
    ADD CONSTRAINT fk_charzs_chars
    FOREIGN KEY (feature)
    REFERENCES features (code);

-- favorites.user_id → users.id
ALTER TABLE favorites
    ADD CONSTRAINT fk_favorites_users
    FOREIGN KEY (user_id)
    REFERENCES users (id);

-- favorites.asset → assets.id
ALTER TABLE favorites
    ADD CONSTRAINT fk_favorites_assets
    FOREIGN KEY (asset)
    REFERENCES assets (id);

-- actions.asset → assets.id
ALTER TABLE actions 
    ADD CONSTRAINT fk_actions_assets
    FOREIGN KEY (asset)
    REFERENCES assets (id);

-- actions.user_id → users.id
ALTER TABLE actions
    ADD CONSTRAINT fk_actions_users
    FOREIGN KEY (user_id)
    REFERENCES users (id);

-- actions.parent → actions.id
ALTER TABLE actions
    ADD CONSTRAINT fk_actions_actions
    FOREIGN KEY (parent)
    REFERENCES actions(id);

-- asset_relations.source → assets.id
ALTER TABLE asset_relations 
    ADD CONSTRAINT fk_asset_rel_source_assets
    FOREIGN KEY (source)
    REFERENCES assets (id);

-- asset_relations.target → assets.id
ALTER TABLE asset_relations 
    ADD CONSTRAINT fk_asset_rel_target_assets
    FOREIGN KEY (target)
    REFERENCES assets (id);

-- **********************************
-- ***** Table lists/list_items *****
-- **********************************

-- ===== List: Feature Type =====
INSERT INTO lists (code, name, description, type, module, is_active) VALUES (
    'FEAT_TYPE', 'List of feature types for system configuration',
    'List that classifies the types of features (e.g., General, Technical, Commercial, Usability, Documentation and Platform) available in SynapxIA.',
    'LIST_OF_VALUES', 'CATALOG', TRUE);
INSERT INTO list_items (list, value, label, sort_order, is_active) VALUES
    ('FEAT_TYPE', 'GENERAL', 'General', 10, TRUE),
    ('FEAT_TYPE', 'TECHNICAL', 'Technical', 20, TRUE),
    ('FEAT_TYPE', 'COMMERCIAL', 'Commercial', 30, TRUE),
    ('FEAT_TYPE', 'USABILITY', 'Usability', 40, TRUE),
    ('FEAT_TYPE', 'DOCUMENTATION', 'Documentation', 50, TRUE);

-- ===== List: Visibility Level =====
INSERT INTO lists (code, name, description, type, module, is_active) VALUES (
    'VISIBILITY_LEVEL', 'List of visibility levels for system configuration elements',
    'List that classifies the visibility of elements in SynapxIA (e.g., Public, Private, Internal).',
    'LIST_OF_VALUES', 'CATALOG', TRUE);
INSERT INTO list_items (list, value, label, sort_order, is_active) VALUES
    ('VISIBILITY_LEVEL', 'PUBLIC', 'Public', 10, TRUE),     -- visible to all users in the organization
    ('VISIBILITY_LEVEL', 'INTERNAL', 'Internal', 30, TRUE), -- visible only to users in a specific organizational unit
    ('VISIBILITY_LEVEL', 'PRIVATE', 'Private', 20, TRUE);   -- visible only to users in a specific team

-- ===== List: Asset Relation Type =====
INSERT INTO lists (code, name, description, type, module, is_active) VALUES (
    'ASSET_REL_TYPE', 'List asset relation types for system configuration',
    'List that classifies the types of relationships between assets in SynapxIA (e.g., Depends On, Related To, Similar To, Part Of).',
    'LIST_OF_VALUES', 'CATALOG', TRUE);
INSERT INTO list_items (list, value, label, sort_order, is_active) VALUES
    ('ASSET_REL_TYPE', 'DEPENDS_ON', 'Depends On', 10, TRUE),
    ('ASSET_REL_TYPE', 'RELATED_TO', 'Related To', 20, TRUE),
    ('ASSET_REL_TYPE', 'SIMILAR_TO', 'Similar To', 30, TRUE),
    ('ASSET_REL_TYPE', 'PART_OF', 'Part Of', 40, TRUE),
    ('ASSET_REL_TYPE', 'USED_BY', 'Used By', 50, TRUE),
    ('ASSET_REL_TYPE', 'EXTENDS', 'Extends', 60, TRUE),
    ('ASSET_REL_TYPE', 'CONTAINS', 'Contains', 70, TRUE),
    ('ASSET_REL_TYPE', 'INSPIRED_BY', 'Inspired By', 80, TRUE);

-- ===== List: Asset Type =====
INSERT INTO lists (code, name, description, type, module, is_active) VALUES (
    'ASSET_TYPE', 'List of asset types for system configuration',
    'List that classifies the types of assets in SynapxIA (e.g., Asset, Initiative).',
    'LIST_OF_VALUES', 'CATALOG', TRUE);
INSERT INTO list_items (list, value, label, sort_order, is_active) VALUES
    ('ASSET_TYPE', 'RESOURCE', 'Resource', 10, TRUE),
    ('ASSET_TYPE', 'INITIATIVE', 'Initiative', 20, TRUE);

-- ===== List: Action Kind =====
INSERT INTO lists (code, name, description, type, module, is_active) VALUES (
    'ACTION_KIND', 'List of action kinds for system configuration',
    'List that classifies the kinds of actions in SynapxIA (e.g., Contribution, Collaboration).',
    'LIST_OF_VALUES', 'CATALOG', TRUE);
INSERT INTO list_items (list, value, label, sort_order, is_active) VALUES
    ('ACTION_KIND', 'CONTRIBUTION', 'Contribution', 10, TRUE),   -- for Actions on Resources
    ('ACTION_KIND', 'COLLABORATION', 'Collaboration', 20, TRUE); -- for Actions on Initiatives;

-- ===== List: Asset Status for Resources =====
INSERT INTO lists (code, name, description, type, module, is_active) VALUES (
    'RESOURCE_STATUS', 'List of resource statuses (asset statuses) for system configuration',
    'List that classifies the statuses of resources in SynapxIA.',
    'LIST_OF_VALUES', 'CATALOG', TRUE);
INSERT INTO list_items (list, value, label, sort_order, is_active) VALUES
    ('RESOURCE_STATUS', '1-PROPOSED', '1-Proposed', 10, TRUE),
    ('RESOURCE_STATUS', '2-FEEDBACK', '2-Feedback Provided', 20, TRUE),
    ('RESOURCE_STATUS', '3-PUBLISHED', '3-Published', 30, TRUE),
    ('RESOURCE_STATUS', '4-REJECTED', '4-Rejected', 40, TRUE),
    ('RESOURCE_STATUS', '5-DEPRECATED', '5-Deprecated', 50, TRUE),
    ('RESOURCE_STATUS', '6-IN_USE', '6-In Use', 60, TRUE);

-- ===== List: Action Type for Contributions =====
INSERT INTO lists (code, name, description, type, module, is_active) VALUES (
    'CONTRIB_TYPE', 'List of contribution types (action types) for system configuration',
    'List that classifies the types of contribution that users can perform on resources in SynapxIA.',
    'LIST_OF_VALUES', 'CATALOG', TRUE);
INSERT INTO list_items (list, value, label, sort_order, is_active) VALUES
    ('CONTRIB_TYPE', '1-PROPOSAL', '1-Proposal', 10, TRUE),
    ('CONTRIB_TYPE', '2-REVIEW', '2-Review', 20, TRUE),
    ('CONTRIB_TYPE', '3-MODIFICATION', '3-Modification', 30, TRUE),
    ('CONTRIB_TYPE', '3-PUBLICATION', '3-Publication', 40, TRUE),
    ('CONTRIB_TYPE', '4-REJECTION', '4-Rejection', 50, TRUE),
    ('CONTRIB_TYPE', '5-DEPRECATION', '5-Deprecation', 60, TRUE),
    ('CONTRIB_TYPE', '6-USAGE', '6-Usage', 70, TRUE),
    ('CONTRIB_TYPE', '6-VOTE', '6-Vote', 80, TRUE),
    ('CONTRIB_TYPE', '6-COMMENT', '6-Comment', 90, TRUE),
    ('CONTRIB_TYPE', '6-QUESTION', '6-Question', 100, TRUE),
    ('CONTRIB_TYPE', '6-ANSWER', '6-Answer', 110, TRUE),
    ('CONTRIB_TYPE', '6-REQUEST', '6-Request', 120, TRUE);

-- ===== List: Asset Status for Initiatives =====
INSERT INTO lists (code, name, description, type, module, is_active) VALUES (
    'INITIATIVE_STATUS', 'List of initiative statuses (asset statuses) for system configuration',
    'List that classifies the statuses of initiatives in SynapxIA.',
    'LIST_OF_VALUES', 'CATALOG', TRUE);
INSERT INTO list_items (list, value, label, sort_order, is_active) VALUES
    ('INITIATIVE_STATUS', '1-ACTIVATED', '1-Activated', 10, TRUE),
    ('INITIATIVE_STATUS', '2-ASSESSMENT', '2-Assessment', 20, TRUE),
    ('INITIATIVE_STATUS', '3-ENGAGING', '3-Engaging', 30, TRUE),
    ('INITIATIVE_STATUS', '4-DELIVERED', '4-Delivered', 40, TRUE),
    ('INITIATIVE_STATUS', '5-EVOLVING', '5-Evolving', 50, TRUE);

-- ===== List: Action Type for Collaborations =====
INSERT INTO lists (code, name, description, type, module, is_active) VALUES (
    'COLLAB_TYPE', 'List of collaboration types (action types) for system configuration',
    'List that classifies the types of collaboration that users can perform on initiatives in SynapxIA.',
    'LIST_OF_VALUES', 'CATALOG', TRUE);
INSERT INTO list_items (list, value, label, sort_order, is_active) VALUES
    ('COLLAB_TYPE', '1-ACTIVATION', '1-Activation', 10, TRUE),
    ('COLLAB_TYPE', '2-ASSESSMENT', '2-Assessment', 20, TRUE),
    ('COLLAB_TYPE', '3-EXPLORATION', '3-Exploration', 30, TRUE),
    ('COLLAB_TYPE', '3-PROTOTYPING', '3-Prototyping', 33, TRUE),
    ('COLLAB_TYPE', '3-IMPLEMENTATION', '3-Implementation', 36, TRUE),
    ('COLLAB_TYPE', '4-ENABLEMENT', '4-Enablement', 40, TRUE),
    ('COLLAB_TYPE', '5-IMPROVEMENT', '5-Improvement', 50, TRUE),
    ('COLLAB_TYPE', '5-REFACTORING', '5-Refactoring', 52, TRUE),
    ('COLLAB_TYPE', '5-EXPANSION', '5-Expansion', 54, TRUE),
    ('COLLAB_TYPE', '5-VERSIONING', '5-Versioning', 56, TRUE),
    ('COLLAB_TYPE', '5-DEPRECATION', '5-Deprecation', 58, TRUE);
