-- **********************************
-- ***** Tables Digital Library *****
-- **********************************

-- Table assets
CREATE TABLE assets (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    category    VARCHAR(50),
    reference   TEXT,
    status	    VARCHAR(100)  NOT NULL, -- references List_items.value where list='ASSET_STATUS'
	visibility  VARCHAR(100)  NOT NULL, -- references List_items.value where list='VISIBILITY_LEVEL'
	tags        JSONB,
	detail      TEXT,
    unit        VARCHAR(50),
    team        VARCHAR(50),
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ,
    CONSTRAINT pk_assets PRIMARY KEY (id)
);

-- Table characterizations
CREATE TABLE characterizations (
    asset           BIGINT        NOT NULL,
    feature         VARCHAR(50)   NOT NULL,
    value           TEXT, -- Any or references List_items.value where list IN [select code from lists where type='FEATURE']
    detail          TEXT, -- Additional information about the characterization (e.g., rationale, source, etc.)
    is_active       BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ,
    CONSTRAINT pk_characterizations PRIMARY KEY (asset, feature)
);

-- Table favorite_assets
CREATE TABLE favorite_assets (
    user_id     BIGINT       NOT NULL,
    asset       BIGINT       NOT NULL,
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ,
    CONSTRAINT pk_favorite_assets PRIMARY KEY (user_id, asset)
);

-- Table actions
CREATE TABLE actions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    asset          BIGINT        NOT NULL,
    user_id        BIGINT        NOT NULL,
	type	       VARCHAR(100)  NOT NULL, -- references List_items.value where list='ACTION_TYPE'
    content        TEXT,
    reference      TEXT,
    parent         BIGINT,
	detail         TEXT,
    is_active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ,
    CONSTRAINT pk_actions PRIMARY KEY (id)
);

-- Table related_assets
CREATE TABLE related_assets (
    source      BIGINT        NOT NULL,
    target      BIGINT        NOT NULL,
    type        VARCHAR(100)  NOT NULL, -- references List_items.value where list='RELATION_TYPE'
    rationale   TEXT,
    is_active   BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ,
    CONSTRAINT pk_related_assets PRIMARY KEY (source, target) 
);

-- ****************************************
-- ************ Foreign Keys **************
-- ****************************************

-- assets.category → categories.code
ALTER TABLE assets
    ADD CONSTRAINT fk_assets_categories
    FOREIGN KEY (category)
    REFERENCES categories(code);

-- assets.unit → business_units.code
ALTER TABLE assets
    ADD CONSTRAINT fk_assets_business_units
    FOREIGN KEY (unit)
    REFERENCES business_units(code);

-- assets.team → teams.code
ALTER TABLE assets
    ADD CONSTRAINT fk_assets_teams
    FOREIGN KEY (team)
    REFERENCES teams(code);

-- characterizations.asset → assets.id
ALTER TABLE characterizations
    ADD CONSTRAINT fk_charzs_assets
    FOREIGN KEY (asset)
    REFERENCES assets (id);

-- characterizations.feature → features.code
ALTER TABLE characterizations
    ADD CONSTRAINT fk_charzs_chars
    FOREIGN KEY (feature)
    REFERENCES features (code);

-- favorite_assets.user_id → users.id
ALTER TABLE favorite_assets
    ADD CONSTRAINT fk_favorite_assets_users
    FOREIGN KEY (user_id)
    REFERENCES users (id);

-- favorite_assets.asset → assets.id
ALTER TABLE favorite_assets
    ADD CONSTRAINT fk_favorite_assets_assets
    FOREIGN KEY (asset)
    REFERENCES assets (id);

-- actions.asset → assets.id
ALTER TABLE actions 
    ADD CONSTRAINT fk_actions_assets
    FOREIGN KEY (asset)
    REFERENCES assets (id);

-- actions.user_id → users.id
ALTER TABLE actions
    ADD CONSTRAINT fk_actions_users
    FOREIGN KEY (user_id)
    REFERENCES users (id);

-- actions.parent → actions.id
ALTER TABLE actions
    ADD CONSTRAINT fk_actions_actions
    FOREIGN KEY (parent)
    REFERENCES actions(id);

-- related_assets.source → assets.id
ALTER TABLE related_assets 
    ADD CONSTRAINT fk_related_assets_source
    FOREIGN KEY (source)
    REFERENCES assets (id);

-- related_assets.target → assets.id
ALTER TABLE related_assets 
    ADD CONSTRAINT fk_related_assets_target
    FOREIGN KEY (target)
    REFERENCES assets (id);

-- **********************************
-- ***** Table lists/list_items *****
-- **********************************

-- ===== List: Visibility Level =====
INSERT INTO lists (code, name, description, type, module) VALUES (
    'VISIBILITY_LEVEL', 'List of visibility levels for system configuration elements',
    'List that classifies the visibility of elements in SynapxIA (e.g., Public, Private, Internal).',
    'LIST_OF_VALUES', NULL);
INSERT INTO list_items (list, value, label, sort_order) VALUES
    ('VISIBILITY_LEVEL', 'PUBLIC', 'Public', 10),     -- visible to all users in the organization
    ('VISIBILITY_LEVEL', 'INTERNAL', 'Internal', 30), -- visible only to users in a specific organizational unit
    ('VISIBILITY_LEVEL', 'PRIVATE', 'Private', 20);   -- visible only to users in a specific team

-- ===== List: Asset Status =====
INSERT INTO lists (code, name, description, type, module) VALUES (
    'ASSET_STATUS', 'List of asset statuses for system configuration',
    'List that classifies the statuses of resources in SynapxIA.',
    'LIST_OF_VALUES', 'LIB');
INSERT INTO list_items (list, value, label, sort_order) VALUES
    ('ASSET_STATUS', '1-PROPOSED', '1-Proposed', 10),
    ('ASSET_STATUS', '2-FEEDBACK', '2-Feedback Provided', 20),
    ('ASSET_STATUS', '3-PUBLISHED', '3-Published', 30),
    ('ASSET_STATUS', '4-REJECTED', '4-Rejected', 40),
    ('ASSET_STATUS', '5-DEPRECATED', '5-Deprecated', 50),
    ('ASSET_STATUS', '6-IN_USE', '6-In Use', 60);

-- ===== List: Action Type =====
INSERT INTO lists (code, name, description, type, module) VALUES (
    'ACTION_TYPE', 'List of action types for system configuration',
    'List that classifies the types of actions that users can perform on assets in SynapxIA.',
    'LIST_OF_VALUES', 'LIB');
INSERT INTO list_items (list, value, label, sort_order) VALUES
    ('ACTION_TYPE', '1-PROPOSAL', '1-Proposal', 10),
    ('ACTION_TYPE', '2-REVIEW', '2-Review', 20),
    ('ACTION_TYPE', '3-MODIFICATION', '3-Modification', 30),
    ('ACTION_TYPE', '3-PUBLICATION', '3-Publication', 40),
    ('ACTION_TYPE', '4-REJECTION', '4-Rejection', 50),
    ('ACTION_TYPE', '5-DEPRECATION', '5-Deprecation', 60),
    ('ACTION_TYPE', '6-USAGE', '6-Usage', 70),
    ('ACTION_TYPE', '6-VOTE', '6-Vote', 80),
    ('ACTION_TYPE', '6-COMMENT', '6-Comment', 90),
    ('ACTION_TYPE', '6-QUESTION', '6-Question', 100),
    ('ACTION_TYPE', '6-ANSWER', '6-Answer', 110),
    ('ACTION_TYPE', '6-REQUEST', '6-Request', 120);

-- ===== List: Asset Relation Type =====
INSERT INTO lists (code, name, description, type, module) VALUES (
    'RELATION_TYPE', 'List of relation types for system configuration',
    'List that classifies the types of relationships between elements in SynapxIA (e.g., Depends On, Related To, Similar To, Part Of).',
    'LIST_OF_VALUES', NULL);
INSERT INTO list_items (list, value, label, sort_order) VALUES
    ('RELATION_TYPE', 'DEPENDS_ON', 'Depends On', 10),
    ('RELATION_TYPE', 'RELATED_TO', 'Related To', 20),
    ('RELATION_TYPE', 'SIMILAR_TO', 'Similar To', 30),
    ('RELATION_TYPE', 'PART_OF', 'Part Of', 40),
    ('RELATION_TYPE', 'USED_BY', 'Used By', 50),
    ('RELATION_TYPE', 'EXTENDS', 'Extends', 60),
    ('RELATION_TYPE', 'CONTAINS', 'Contains', 70),
    ('RELATION_TYPE', 'INSPIRED_BY', 'Inspired By', 80);
