-- **********************************
-- ***** Tables Digital Library *****
-- **********************************

-- Table assets
CREATE TABLE assets (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    category    VARCHAR(50),
    reference   TEXT,
    status	    VARCHAR(100)  NOT NULL, -- references List_items.value where list='ASSET_STATUS'
	tags        JSONB,
	detail      TEXT,
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ,
    CONSTRAINT pk_assets PRIMARY KEY (id)
);

-- Table characterizations
CREATE TABLE characterizations (
    asset           BIGINT        NOT NULL,
    feature         VARCHAR(50)   NOT NULL,
    value           TEXT, -- Any or references List_items.value where list IN [select code from lists where type='FEATURE']
    detail          TEXT, -- Additional information about the characterization (e.g., rationale, source, etc.)
    is_active       BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ,
    CONSTRAINT pk_characterizations PRIMARY KEY (asset, feature)
);

-- Table favorite_assets
CREATE TABLE favorite_assets (
    user_id     BIGINT       NOT NULL,
    asset       BIGINT       NOT NULL,
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ,
    CONSTRAINT pk_favorite_assets PRIMARY KEY (user_id, asset)
);

-- Table actions
CREATE TABLE actions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    asset          BIGINT        NOT NULL,
    user_id        BIGINT        NOT NULL,
	type	       VARCHAR(100)  NOT NULL, -- references List_items.value where list='ACTION_TYPE'
    content        TEXT,
    reference      TEXT,
    parent         BIGINT,
	detail         TEXT,
    is_active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ,
    CONSTRAINT pk_actions PRIMARY KEY (id)
);

-- Table related_assets
CREATE TABLE related_assets (
    source      BIGINT        NOT NULL,
    target      BIGINT        NOT NULL,
    type        VARCHAR(100)  NOT NULL, -- references List_items.value where list='RELATION_TYPE'
    rationale   TEXT,
    is_active   BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ,
    CONSTRAINT pk_related_assets PRIMARY KEY (source, target, type) 
);

-- Table asset_permissions
CREATE TABLE asset_permissions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    asset         BIGINT        NOT NULL,
    target_type   VARCHAR(100)  NOT NULL, -- references List_items.value where list='TARGET_TYPE'
    target_code   VARCHAR(50)   NOT NULL, -- the recipient identifier
    access_level  VARCHAR(100)  NOT NULL, -- references List_items.value where list='ACCESS_LEVEL'
    valid_from    TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    valid_to      TIMESTAMPTZ,
    CONSTRAINT pk_asset_permissions PRIMARY KEY (id)
);

-- ****************************************
-- ************ Foreign Keys **************
-- ****************************************

-- assets.category → categories.code
ALTER TABLE assets
    ADD CONSTRAINT fk_assets_categories
    FOREIGN KEY (category)
    REFERENCES categories(code);

-- characterizations.asset → assets.id
ALTER TABLE characterizations
    ADD CONSTRAINT fk_charzs_assets
    FOREIGN KEY (asset)
    REFERENCES assets (id);

-- characterizations.feature → features.code
ALTER TABLE characterizations
    ADD CONSTRAINT fk_charzs_chars
    FOREIGN KEY (feature)
    REFERENCES features (code);

-- favorite_assets.user_id → users.id
ALTER TABLE favorite_assets
    ADD CONSTRAINT fk_favorite_assets_users
    FOREIGN KEY (user_id)
    REFERENCES users (id);

-- favorite_assets.asset → assets.id
ALTER TABLE favorite_assets
    ADD CONSTRAINT fk_favorite_assets_assets
    FOREIGN KEY (asset)
    REFERENCES assets (id);

-- asset_permissions.asset → assets.id
ALTER TABLE asset_permissions
    ADD CONSTRAINT fk_asset_permissions_assets
    FOREIGN KEY (asset)
    REFERENCES assets (id);

-- actions.asset → assets.id
ALTER TABLE actions 
    ADD CONSTRAINT fk_actions_assets
    FOREIGN KEY (asset)
    REFERENCES assets (id);

-- actions.user_id → users.id
ALTER TABLE actions
    ADD CONSTRAINT fk_actions_users
    FOREIGN KEY (user_id)
    REFERENCES users (id);

-- actions.parent → actions.id
ALTER TABLE actions
    ADD CONSTRAINT fk_actions_actions
    FOREIGN KEY (parent)
    REFERENCES actions(id);

-- related_assets.source → assets.id
ALTER TABLE related_assets 
    ADD CONSTRAINT fk_related_assets_source
    FOREIGN KEY (source)
    REFERENCES assets (id);

-- related_assets.target → assets.id
ALTER TABLE related_assets 
    ADD CONSTRAINT fk_related_assets_target
    FOREIGN KEY (target)
    REFERENCES assets (id);

-- **********************************
-- ***** Table lists/list_items *****
-- **********************************

-- ===== List: Asset Status =====
INSERT INTO lists (code, name, description, type, module) VALUES (
    'ASSET_STATUS', 'List of asset statuses for system configuration',
    'List that classifies the statuses of resources in SynapxIA.',
    'LIST_OF_VALUES', 'LIB');
INSERT INTO list_items (list, lang, value, label, sort_order) VALUES
    ('ASSET_STATUS', 'en', '1-PROPOSED', '1-Proposed', 10),
    ('ASSET_STATUS', 'en', '2-FEEDBACK', '2-Feedback Provided', 20),
    ('ASSET_STATUS', 'en', '3-PUBLISHED', '3-Published', 30),
    ('ASSET_STATUS', 'en', '4-REJECTED', '4-Rejected', 40),
    ('ASSET_STATUS', 'en', '5-DEPRECATED', '5-Deprecated', 50),
    ('ASSET_STATUS', 'en', '6-IN_USE', '6-In Use', 60);

-- ===== List: Action Type =====
INSERT INTO lists (code, name, description, type, module) VALUES (
    'ACTION_TYPE', 'List of action types for system configuration',
    'List that classifies the types of actions that users can perform on assets in SynapxIA.',
    'LIST_OF_VALUES', 'LIB');
INSERT INTO list_items (list, lang, value, label, sort_order) VALUES
    ('ACTION_TYPE', 'en', '1-PROPOSAL', '1-Proposal', 10),          -- user with MANAGE in access_level can propose and publish at same time
    ('ACTION_TYPE', 'en', '2-REVIEW', '2-Review', 20),              -- only users with MANAGE in access_level can review
    ('ACTION_TYPE', 'en', '3-MODIFICATION', '3-Modification', 30),  -- only owner can modify
    ('ACTION_TYPE', 'en', '3-PUBLICATION', '3-Publication', 40),    -- only users with MANAGE in access_level can publish
    ('ACTION_TYPE', 'en', '4-REJECTION', '4-Rejection', 50),        -- only users with MANAGE in access_level can reject
    ('ACTION_TYPE', 'en', '5-DEPRECATION', '5-Deprecation', 60),    -- only users with MANAGE in access_level can deprecate
    ('ACTION_TYPE', 'en', '6-VERSIONING', '6-Versioning', 70),      -- only users with MANAGE in access_level can create new version, modification with versioning creates a new asset with reference to the previous one and a relation of type 'Extends'
    ('ACTION_TYPE', 'en', '6-USAGE', '6-Usage', 70),
    ('ACTION_TYPE', 'en', '6-VOTE', '6-Vote', 80),
    ('ACTION_TYPE', 'en', '6-COMMENT', '6-Comment', 90),
    ('ACTION_TYPE', 'en', '6-QUESTION', '6-Question', 100),
    ('ACTION_TYPE', 'en', '6-ANSWER', '6-Answer', 110),
    ('ACTION_TYPE', 'en', '6-REQUEST', '6-Request', 120);

-- ===== List: Asset Relation Type =====
INSERT INTO lists (code, name, description, type, module) VALUES (
    'RELATION_TYPE', 'List of relation types for system configuration',
    'List that classifies the types of relationships between elements in SynapxIA (e.g., Depends On, Related To, Similar To, Part Of).',
    'LIST_OF_VALUES', NULL);
INSERT INTO list_items (list, lang, value, label, sort_order) VALUES
    ('RELATION_TYPE', 'en', 'DEPENDS_ON', 'Depends On', 10),
    ('RELATION_TYPE', 'en', 'RELATED_TO', 'Related To', 20),
    ('RELATION_TYPE', 'en', 'SIMILAR_TO', 'Similar To', 30),
    ('RELATION_TYPE', 'en', 'PART_OF', 'Part Of', 40),
    ('RELATION_TYPE', 'en', 'USED_BY', 'Used By', 50),
    ('RELATION_TYPE', 'en', 'EXTENDS', 'Extends', 60),
    ('RELATION_TYPE', 'en', 'CONTAINS', 'Contains', 70),
    ('RELATION_TYPE', 'en', 'INSPIRED_BY', 'Inspired By', 80);

-- ===== List: Target Type =====
INSERT INTO lists (code, name, description, type, module) VALUES (
    'TARGET_TYPE', 'List of target types for system configuration',
    'List that classifies the types of targets for access control in SynapxIA.',
    'LIST_OF_VALUES', NULL);
INSERT INTO list_items (list, lang, value, label, sort_order) VALUES
    ('TARGET_TYPE', 'en', 'USER', 'Users', 10),
    ('TARGET_TYPE', 'en', 'ROLE', 'Roles', 20),
    ('TARGET_TYPE', 'en', 'PROJECT', 'Projects', 30),
    ('TARGET_TYPE', 'en', 'TEAM', 'Teams', 40),
    ('TARGET_TYPE', 'en', 'UNIT', 'Units', 50),
    ('TARGET_TYPE', 'en', 'PUBLIC', 'Public', 60);

-- ===== List: Access Level =====
INSERT INTO lists (code, name, description, type, module) VALUES (
    'ACCESS_LEVEL', 'List of access levels for system configuration',
    'List that classifies the levels of access that users can have for elements in SynapxIA.',
    'LIST_OF_VALUES', NULL);
INSERT INTO list_items (list, lang, value, label, sort_order) VALUES
    ('ACCESS_LEVEL', 'en', 'VIEW', 'View', 10),
    ('ACCESS_LEVEL', 'en', 'MANAGE', 'Manage', 20);
