-- **********************************
-- ******* Tables Initiatives *******
-- **********************************

-- Table initiatives
CREATE TABLE initiatives (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name             VARCHAR(100)  NOT NULL,
    description      VARCHAR(500),
	expected_impact  VARCHAR(100)  NOT NULL, -- references List_items.value where list='EXPECTED_IMPACT'
    priority_level   VARCHAR(100)  NOT NULL, -- references List_items.value where list='PRIORITY_LEVEL'
    reference        TEXT,
    status	         VARCHAR(100)  NOT NULL, -- references List_items.value where list='INITIATIVE_STATUS'
	visibility       VARCHAR(100)  NOT NULL, -- references List_items.value where list='VISIBILITY_LEVEL'
	tags             JSONB,
    score            SMALLINT,
	detail           TEXT,
    unit             VARCHAR(50),
    team             VARCHAR(50),
    is_active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ,
    CONSTRAINT pk_initiatives PRIMARY KEY (id)
);

-- Table criterias
CREATE TABLE criterias (
    code        VARCHAR(50)  NOT NULL,
    name        VARCHAR(100)  NOT NULL,
    description VARCHAR(500),
    list        VARCHAR(50),  -- references Lists.code where type='CRITERIA'
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ,
    CONSTRAINT pk_criterias PRIMARY KEY (code)
);

-- Table diagnostics
CREATE TABLE diagnostics (
    init            BIGINT   NOT NULL,
    criteria        VARCHAR(50)   NOT NULL,
    creator_score   SMALLINT      NOT NULL, -- references List_items.value where list IN [select code from lists where type='CRITERIA']
    reviewer_score  SMALLINT,               -- references List_items.value where list IN [select code from lists where type='CRITERIA']
    rationale       TEXT,
    is_active       BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ,
    CONSTRAINT pk_diagnostics PRIMARY KEY (init, criteria)
);

-- Table favorite_inits
CREATE TABLE favorite_inits (
    user_id     BIGINT       NOT NULL,
    init        BIGINT       NOT NULL,
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ,
    CONSTRAINT pk_favorite_inits PRIMARY KEY (user_id, init)
);

-- Table collaborations
CREATE TABLE collaborations (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    init           BIGINT        NOT NULL,
    user_id        BIGINT        NOT NULL,
	type	       VARCHAR(100)  NOT NULL, -- references List_items.value where list='COLLAB_TYPE'
    content        TEXT,
    reference      TEXT,
    parent         BIGINT,
	detail         TEXT,
    is_active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ,
    CONSTRAINT pk_collaborations PRIMARY KEY (id)
);

-- Table related_inits
CREATE TABLE related_inits (
    source      BIGINT        NOT NULL,
    target      BIGINT        NOT NULL,
    type        VARCHAR(100)  NOT NULL, -- references List_items.value where list='RELATION_TYPE'
    rationale   TEXT,
    is_active   BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ,
    CONSTRAINT pk_related_inits PRIMARY KEY (source, target) 
);

-- ****************************************
-- ************ Foreign Keys **************
-- ****************************************

-- initiatives.unit → business_units.code
ALTER TABLE initiatives
    ADD CONSTRAINT fk_initiatives_business_units
    FOREIGN KEY (unit)
    REFERENCES business_units(code);

-- initiatives.team → teams.code
ALTER TABLE initiatives
    ADD CONSTRAINT fk_initiatives_teams
    FOREIGN KEY (team)
    REFERENCES teams(code);

-- diagnostics.init → initiatives.id
ALTER TABLE diagnostics
    ADD CONSTRAINT fk_diagnostics_initiatives
    FOREIGN KEY (init)
    REFERENCES initiatives (id);

-- diagnostics.criteria → criterias.code
ALTER TABLE diagnostics
    ADD CONSTRAINT fk_diagnostics_criterias
    FOREIGN KEY (criteria)
    REFERENCES criterias (code);

-- favorite_inits.user_id → users.id
ALTER TABLE favorite_inits
    ADD CONSTRAINT fk_favorite_inits_users
    FOREIGN KEY (user_id)
    REFERENCES users (id);

-- favorite_inits.init → initiatives.id
ALTER TABLE favorite_inits
    ADD CONSTRAINT fk_favorite_inits_initiatives
    FOREIGN KEY (init)
    REFERENCES initiatives (id);

-- collaborations.init → initiatives.id
ALTER TABLE collaborations 
    ADD CONSTRAINT fk_collaborations_initiatives
    FOREIGN KEY (init)
    REFERENCES initiatives (id);

-- collaborations.user_id → users.id
ALTER TABLE collaborations
    ADD CONSTRAINT fk_collaborations_users
    FOREIGN KEY (user_id)
    REFERENCES users (id);

-- collaborations.parent → collaborations.id
ALTER TABLE collaborations
    ADD CONSTRAINT fk_collaborations_collaborations
    FOREIGN KEY (parent)
    REFERENCES collaborations(id);

-- related_inits.source → initiatives.id
ALTER TABLE related_inits 
    ADD CONSTRAINT fk_related_inits_source
    FOREIGN KEY (source)
    REFERENCES initiatives (id);

-- related_inits.target → initiatives.id
ALTER TABLE related_inits 
    ADD CONSTRAINT fk_related_inits_target
    FOREIGN KEY (target)
    REFERENCES initiatives (id);

-- **********************************
-- ***** Table lists/list_items *****
-- **********************************

-- ===== List: Asset Status for Initiatives =====
INSERT INTO lists (code, name, description, type, module, is_active) VALUES (
    'INITIATIVE_STATUS', 'List of initiative statuses for system configuration',
    'List that classifies the statuses of initiatives in SynapxIA.',
    'LIST_OF_VALUES', 'INITS', TRUE);
INSERT INTO list_items (list, value, label, sort_order, is_active) VALUES
    ('INITIATIVE_STATUS', '1-ACTIVATED', '1-Activated', 10, TRUE),
    ('INITIATIVE_STATUS', '2-ASSESSMENT', '2-Assessment', 20, TRUE),
    ('INITIATIVE_STATUS', '3-ENGAGING', '3-Engaging', 30, TRUE),
    ('INITIATIVE_STATUS', '4-DELIVERED', '4-Delivered', 40, TRUE),
    ('INITIATIVE_STATUS', '5-EVOLVING', '5-Evolving', 50, TRUE);

-- ===== List: Expected Impact for Initiatives =====
INSERT INTO lists (code, name, description, type, module, is_active) VALUES (
    'EXPECTED_IMPACT', 'List of expected impacts for system configuration',
    'List that classifies the expected impacts of initiatives in SynapxIA.',
    'LIST_OF_VALUES', 'INITS', TRUE);
INSERT INTO list_items (list, value, label, sort_order, is_active) VALUES
    ('EXPECTED_IMPACT', 'TIME_REDUCTION', 'Time Reduction', 10, TRUE),
    ('EXPECTED_IMPACT', 'QUALITY_IMPROVEMENT', 'Quality Improvement', 20, TRUE),
    ('EXPECTED_IMPACT', 'ERROR_REDUCTION', 'Error Reduction', 30, TRUE),
    ('EXPECTED_IMPACT', 'DECISION_SUPPORT', 'Decision Support', 40, TRUE),
    ('EXPECTED_IMPACT', 'IMPROVED_UX', 'Improved User Experience', 50, TRUE),
    ('EXPECTED_IMPACT', 'COST_SAVINGS', 'Cost Savings', 60, TRUE),
    ('EXPECTED_IMPACT', 'REVENUE_INCREASE', 'Revenue Increase', 70, TRUE),
    ('EXPECTED_IMPACT', 'COMPLIANCE_ENHANCEMENT', 'Compliance Enhancement', 80, TRUE),
    ('EXPECTED_IMPACT', 'RISK_REDUCTION', 'Risk Reduction', 90, TRUE),
    ('EXPECTED_IMPACT', 'SCALABILITY_IMPROVEMENT', 'Scalability Improvement', 100, TRUE),
    ('EXPECTED_IMPACT', 'INNOVATION', 'Innovation', 110, TRUE),
    ('EXPECTED_IMPACT', 'OTHER', 'Other', 120, TRUE);

-- ===== List: Priority Level for Initiatives =====
INSERT INTO lists (code, name, description, type, module, is_active) VALUES (
    'PRIORITY_LEVEL', 'List of priority levels for system configuration',
    'List that classifies the priority levels of initiatives in SynapxIA.',
    'LIST_OF_VALUES', 'INITS', TRUE);
INSERT INTO list_items (list, value, label, sort_order, is_active) VALUES
    ('PRIORITY_LEVEL', 'HIGH', 'High', 10, TRUE),
    ('PRIORITY_LEVEL', 'MEDIUM', 'Medium', 20, TRUE),
    ('PRIORITY_LEVEL', 'LOW', 'Low', 30, TRUE);
 
-- ===== List: Action Type for Collaborations =====
INSERT INTO lists (code, name, description, type, module, is_active) VALUES (
    'COLLAB_TYPE', 'List of collaboration types for system configuration',
    'List that classifies the types of collaboration that users can perform on initiatives in SynapxIA.',
    'LIST_OF_VALUES', 'INITS', TRUE);
INSERT INTO list_items (list, value, label, sort_order, is_active) VALUES
    ('COLLAB_TYPE', '1-ACTIVATION', '1-Activation', 10, TRUE),
    ('COLLAB_TYPE', '2-ASSESSMENT', '2-Assessment', 20, TRUE),
    ('COLLAB_TYPE', '3-EXPLORATION', '3-Exploration', 30, TRUE),
    ('COLLAB_TYPE', '3-PROTOTYPING', '3-Prototyping', 33, TRUE),
    ('COLLAB_TYPE', '3-IMPLEMENTATION', '3-Implementation', 36, TRUE),
    ('COLLAB_TYPE', '4-ENABLEMENT', '4-Enablement', 40, TRUE),
    ('COLLAB_TYPE', '5-IMPROVEMENT', '5-Improvement', 50, TRUE),
    ('COLLAB_TYPE', '5-REFACTORING', '5-Refactoring', 52, TRUE),
    ('COLLAB_TYPE', '5-EXPANSION', '5-Expansion', 54, TRUE),
    ('COLLAB_TYPE', '5-VERSIONING', '5-Versioning', 56, TRUE),
    ('COLLAB_TYPE', '5-DEPRECATION', '5-Deprecation', 58, TRUE);
