-- **********************************
-- ******* Tables Initiatives *******
-- **********************************

-- Table initiatives
CREATE TABLE initiatives (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name             VARCHAR(100)  NOT NULL,
    description      VARCHAR(500),
	expected_impact  VARCHAR(100)  NOT NULL, -- references List_items.value where list='EXPECTED_IMPACT'
    priority_level   VARCHAR(100)  NOT NULL, -- references List_items.value where list='PRIORITY_LEVEL'
    reference        TEXT,
    status	         VARCHAR(100)  NOT NULL, -- references List_items.value where list='INITIATIVE_STATUS'
	tags             JSONB,
	detail           TEXT,
    score            SMALLINT,
    is_active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ,
    CONSTRAINT pk_initiatives PRIMARY KEY (id)
);

-- Table criterias
CREATE TABLE criterias (
    code        VARCHAR(50)   NOT NULL,
    name        VARCHAR(100)  NOT NULL,
    description VARCHAR(500),
    list        VARCHAR(50),  -- references Lists.code where type='CRITERIA'
    is_active   BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ,
    CONSTRAINT pk_criterias PRIMARY KEY (code)
);

-- Table diagnostics
CREATE TABLE diagnostics (
    init            BIGINT        NOT NULL,
    criteria        VARCHAR(50)   NOT NULL,
    creator_score   SMALLINT      NOT NULL, -- references List_items.value where list IN [select code from lists where type='CRITERIA']
    reviewer_score  SMALLINT,               -- references List_items.value where list IN [select code from lists where type='CRITERIA']
    rationale       TEXT,
    is_active       BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ,
    CONSTRAINT pk_diagnostics PRIMARY KEY (init, criteria)
);

-- Table favorite_inits
CREATE TABLE favorite_inits (
    user_id     BIGINT       NOT NULL,
    init        BIGINT       NOT NULL,
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ,
    CONSTRAINT pk_favorite_inits PRIMARY KEY (user_id, init)
);

-- Table collaborations
CREATE TABLE collaborations (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    init             BIGINT        NOT NULL,
    user_id          BIGINT        NOT NULL,
	type	         VARCHAR(100)  NOT NULL, -- references List_items.value where list='COLLAB_TYPE'
    workflow_status  VARCHAR(100),           -- references List_items.value where list='WORKFLOW_STATUS'
    content          TEXT,
    reference        TEXT,
    parent           BIGINT,
	detail           TEXT,
    is_active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ,
    CONSTRAINT pk_collaborations PRIMARY KEY (id)
);

-- Table related_inits
CREATE TABLE related_inits (
    source      BIGINT        NOT NULL,
    target      BIGINT        NOT NULL,
    type        VARCHAR(100)  NOT NULL, -- references List_items.value where list='RELATION_TYPE'
    rationale   TEXT,
    is_active   BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ,
    CONSTRAINT pk_related_inits PRIMARY KEY (source, target, type) 
);

-- Table init_permissions
CREATE TABLE init_permissions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    init          BIGINT        NOT NULL,
    target_type   VARCHAR(100)  NOT NULL, -- references List_items.value where list='TARGET_TYPE'
    target_code   VARCHAR(50)   NOT NULL, -- the recipient identifier
    access_level  VARCHAR(100)  NOT NULL, -- references List_items.value where list='ACCESS_LEVEL'
    valid_from    TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    valid_to      TIMESTAMPTZ,
    CONSTRAINT pk_init_permissions PRIMARY KEY (id)
);

-- ****************************************
-- ************ Foreign Keys **************
-- ****************************************

-- diagnostics.init → initiatives.id
ALTER TABLE diagnostics
    ADD CONSTRAINT fk_diagnostics_initiatives
    FOREIGN KEY (init)
    REFERENCES initiatives (id);

-- diagnostics.criteria → criterias.code
ALTER TABLE diagnostics
    ADD CONSTRAINT fk_diagnostics_criterias
    FOREIGN KEY (criteria)
    REFERENCES criterias (code);

-- favorite_inits.user_id → users.id
ALTER TABLE favorite_inits
    ADD CONSTRAINT fk_favorite_inits_users
    FOREIGN KEY (user_id)
    REFERENCES users (id);

-- favorite_inits.init → initiatives.id
ALTER TABLE favorite_inits
    ADD CONSTRAINT fk_favorite_inits_initiatives
    FOREIGN KEY (init)
    REFERENCES initiatives (id);

-- init_permissions.init → initiatives.id
ALTER TABLE init_permissions
    ADD CONSTRAINT fk_init_permissions_initiatives
    FOREIGN KEY (init)
    REFERENCES initiatives (id);

-- collaborations.init → initiatives.id
ALTER TABLE collaborations 
    ADD CONSTRAINT fk_collaborations_initiatives
    FOREIGN KEY (init)
    REFERENCES initiatives (id);

-- collaborations.user_id → users.id
ALTER TABLE collaborations
    ADD CONSTRAINT fk_collaborations_users
    FOREIGN KEY (user_id)
    REFERENCES users (id);

-- collaborations.parent → collaborations.id
ALTER TABLE collaborations
    ADD CONSTRAINT fk_collaborations_collaborations
    FOREIGN KEY (parent)
    REFERENCES collaborations(id);

-- related_inits.source → initiatives.id
ALTER TABLE related_inits 
    ADD CONSTRAINT fk_related_inits_source
    FOREIGN KEY (source)
    REFERENCES initiatives (id);

-- related_inits.target → initiatives.id
ALTER TABLE related_inits 
    ADD CONSTRAINT fk_related_inits_target
    FOREIGN KEY (target)
    REFERENCES initiatives (id);

-- **********************************
-- ***** Table lists/list_items *****
-- **********************************

-- ===== List: Asset Status for Initiatives =====
INSERT INTO lists (code, name, description, type, module) VALUES (
    'INITIATIVE_STATUS', 'List of initiative statuses for system configuration',
    'List that classifies the statuses of initiatives in SynapxIA.',
    'LIST_OF_VALUES', 'INITS');
INSERT INTO list_items (list, lang, value, label, sort_order) VALUES
    ('INITIATIVE_STATUS', 'en', '1-ACTIVATED', '1-Activated', 10),
    ('INITIATIVE_STATUS', 'en', '2-ASSESSMENT', '2-Assessment', 20),
    ('INITIATIVE_STATUS', 'en', '3-ENGAGING', '3-Engaging', 30),
    ('INITIATIVE_STATUS', 'en', '4-DELIVERED', '4-Delivered', 40),
    ('INITIATIVE_STATUS', 'en', '5-EVOLVING', '5-Evolving', 50);

-- ===== List: Expected Impact for Initiatives =====
INSERT INTO lists (code, name, description, type, module) VALUES (
    'EXPECTED_IMPACT', 'List of expected impacts for system configuration',
    'List that classifies the expected impacts of initiatives in SynapxIA.',
    'LIST_OF_VALUES', 'INITS');
INSERT INTO list_items (list, lang, value, label, sort_order) VALUES
    ('EXPECTED_IMPACT', 'en', 'TIME_REDUCTION', 'Time Reduction', 10),
    ('EXPECTED_IMPACT', 'en', 'QUALITY_IMPROVEMENT', 'Quality Improvement', 20),
    ('EXPECTED_IMPACT', 'en', 'ERROR_REDUCTION', 'Error Reduction', 30),
    ('EXPECTED_IMPACT', 'en', 'DECISION_SUPPORT', 'Decision Support', 40),
    ('EXPECTED_IMPACT', 'en', 'IMPROVED_UX', 'Improved User Experience', 50),
    ('EXPECTED_IMPACT', 'en', 'COST_SAVINGS', 'Cost Savings', 60),
    ('EXPECTED_IMPACT', 'en', 'REVENUE_INCREASE', 'Revenue Increase', 70),
    ('EXPECTED_IMPACT', 'en', 'COMPLIANCE_ENHANCEMENT', 'Compliance Enhancement', 80),
    ('EXPECTED_IMPACT', 'en', 'RISK_REDUCTION', 'Risk Reduction', 90),
    ('EXPECTED_IMPACT', 'en', 'SCALABILITY_IMPROVEMENT', 'Scalability Improvement', 100),
    ('EXPECTED_IMPACT', 'en', 'INNOVATION', 'Innovation', 110),
    ('EXPECTED_IMPACT', 'en', 'OTHER', 'Other', 120);

-- ===== List: Priority Level for Initiatives =====
INSERT INTO lists (code, name, description, type, module) VALUES (
    'PRIORITY_LEVEL', 'List of priority levels for system configuration',
    'List that classifies the priority levels of initiatives in SynapxIA.',
    'LIST_OF_VALUES', 'INITS');
INSERT INTO list_items (list, lang, value, label, sort_order) VALUES
    ('PRIORITY_LEVEL', 'en', 'HIGH', 'High', 10),
    ('PRIORITY_LEVEL', 'en', 'MEDIUM', 'Medium', 20),
    ('PRIORITY_LEVEL', 'en', 'LOW', 'Low', 30);
 
-- ===== List: Action Type for Collaborations =====
INSERT INTO lists (code, name, description, type, module) VALUES (
    'COLLAB_TYPE', 'List of collaboration types for system configuration',
    'List that classifies the types of collaboration that users can perform on initiatives in SynapxIA.',
    'LIST_OF_VALUES', 'INITS');
INSERT INTO list_items (list, lang, value, label, sort_order) VALUES
    ('COLLAB_TYPE', 'en', '1-ACTIVATION', '1-Activation', 10),
    ('COLLAB_TYPE', 'en', '2-ASSESSMENT', '2-Assessment', 20),
    ('COLLAB_TYPE', 'en', '3-EXPLORATION', '3-Exploration', 30),
    ('COLLAB_TYPE', 'en', '3-PROTOTYPING', '3-Prototyping', 33),
    ('COLLAB_TYPE', 'en', '3-IMPLEMENTATION', '3-Implementation', 36),
    ('COLLAB_TYPE', 'en', '4-ENABLEMENT', '4-Enablement', 40),
    ('COLLAB_TYPE', 'en', '5-IMPROVEMENT', '5-Improvement', 50),
    ('COLLAB_TYPE', 'en', '5-REFACTORING', '5-Refactoring', 52),
    ('COLLAB_TYPE', 'en', '5-EXPANSION', '5-Expansion', 54),
    ('COLLAB_TYPE', 'en', '5-VERSIONING', '5-Versioning', 56),
    ('COLLAB_TYPE', 'en', '5-DEPRECATION', '5-Deprecation', 58);

-- **********************************
-- ****** Lists for Criterias *******
-- **********************************

INSERT INTO lists (code, name, description, module, type) VALUES
('CLARITY_MATURITY', 'Clarity and maturity of the need', 'Level of definition of the need', 'INITS', 'CRITERIA'),
('SUPPORT_OBJECTIVE', 'Support objective', 'Type of support required', 'INITS', 'CRITERIA'),
('COMPLEXITY', 'Technical and functional complexity', 'Level of solution complexity', 'INITS', 'CRITERIA'),
('DATA_INTEGRATIONS', 'Data and integrations', 'Use of data and integrations', 'INITS', 'CRITERIA'),
('RISK_IMPACT', 'Operational risk and impact', 'Level of operational risk', 'INITS', 'CRITERIA'),
('SUSTAINABILITY', 'Sustainability and expected adoption level', 'Level of usage and adoption', 'INITS', 'CRITERIA');

-- ===== 1. Clarity and maturity =====
INSERT INTO list_items (list, lang, value, label, sort_order) VALUES
('CLARITY_MATURITY', 'en', '1', 'Exploratory or not yet well defined', 1),
('CLARITY_MATURITY', 'en', '2', 'Partially defined and requires validation', 2),
('CLARITY_MATURITY', 'en', '3', 'Scope and objectives are clearly defined', 3);
-- 1. Traducciones para Claridad y madurez
INSERT INTO list_items (list, lang, value, label, sort_order) VALUES
('CLARITY_MATURITY', 'es', '1', 'Exploratoria o aún no está bien definida', 1),
('CLARITY_MATURITY', 'es', '2', 'Definida de forma parcial y requiere validación', 2),
('CLARITY_MATURITY', 'es', '3', 'El alcance y los objetivos están claramente definidos', 3);

-- ===== 2. Support objective =====
INSERT INTO list_items (list, lang, value, label, sort_order) VALUES
('SUPPORT_OBJECTIVE', 'en', '1', 'Requires guidance, training, recommendations, or templates', 1),
('SUPPORT_OBJECTIVE', 'en', '2', 'Requires validating an idea through testing or prototyping', 2),
('SUPPORT_OBJECTIVE', 'en', '3', 'Requires an operational solution for real use', 3);
-- 2. Traducciones para Objetivo del acompañamiento
INSERT INTO list_items (list, lang, value, label, sort_order) VALUES
('SUPPORT_OBJECTIVE', 'es', '1', 'Requiere guía, formación, recomendaciones o plantillas', 1),
('SUPPORT_OBJECTIVE', 'es', '2', 'Requiere validar una idea mediante prueba o prototipo', 2),
('SUPPORT_OBJECTIVE', 'es', '3', 'Requiere una solución operativa para uso real', 3);

-- ===== 3. Technical complexity =====
INSERT INTO list_items (list, lang, value, label, sort_order) VALUES
('COMPLEXITY', 'en', '1', 'Low; does not require complex design or significant process changes', 1),
('COMPLEXITY', 'en', '2', 'Medium; requires designing and testing a functional solution', 2),
('COMPLEXITY', 'en', '3', 'High; requires architecture, development, and significant process adjustments', 3);
-- 3. Traducciones para Complejidad técnica
INSERT INTO list_items (list, lang, value, label, sort_order) VALUES
('COMPLEXITY', 'es', '1', 'Baja; no requiere diseño complejo ni cambios relevantes en el proceso', 1),
('COMPLEXITY', 'es', '2', 'Media; requiere diseñar y probar una solución funcional', 2),
('COMPLEXITY', 'es', '3', 'Alta; requiere arquitectura, desarrollo y ajustes relevantes en el proceso', 3);

-- ===== 4. Data and integrations =====
INSERT INTO list_items (list, lang, value, label, sort_order) VALUES
('DATA_INTEGRATIONS', 'en', '1', 'Does not use critical data or require integrations', 1),
('DATA_INTEGRATIONS', 'en', '2', 'Uses limited data or possible integrations, but not critical', 2),
('DATA_INTEGRATIONS', 'en', '3', 'Uses real or sensitive data or integrates with systems, APIs, or institutional workflows', 3);
-- 4. Traducciones para Datos e integraciones
INSERT INTO list_items (list, lang, value, label, sort_order) VALUES
('DATA_INTEGRATIONS', 'es', '1', 'No usa datos críticos ni requiere integraciones', 1),
('DATA_INTEGRATIONS', 'es', '2', 'Usa datos limitados o integraciones posibles, pero no críticas', 2),
('DATA_INTEGRATIONS', 'es', '3', 'Usa datos reales o sensibles o integración con sistemas, APIs o flujos institucionales', 3);

-- ===== 5. Risk and impact =====
INSERT INTO list_items (list, lang, value, label, sort_order) VALUES
('RISK_IMPACT', 'en', '1', 'Low risk; errors have no significant consequences', 1),
('RISK_IMPACT', 'en', '2', 'Medium risk; requires validation before broader use', 2),
('RISK_IMPACT', 'en', '3', 'High risk; may affect operations, decisions, users, or compliance', 3);
-- 5. Riesgo e impacto
INSERT INTO list_items (list, lang, value, label, sort_order) VALUES
('RISK_IMPACT', 'es', '1', 'Riesgo bajo; error sin consecuencias relevantes', 1),
('RISK_IMPACT', 'es', '2', 'Riesgo medio; requiere validación antes de uso más amplio', 2),
('RISK_IMPACT', 'es', '3', 'Riesgo alto; puede afectar operación, decisiones, usuarios o cumplimiento', 3);

-- ===== 6. Sustainability and adoption =====
INSERT INTO list_items (list, lang, value, label, sort_order) VALUES
('SUSTAINABILITY', 'en', '1', 'One-time or learning use; does not require continuous operation', 1),
('SUSTAINABILITY', 'en', '2', 'Recurring use, but still under evaluation', 2),
('SUSTAINABILITY', 'en', '3', 'Continuous use; requires knowledge transfer, ownership, and evolution over time', 3);
-- 6. Sostenibilidad
INSERT INTO list_items (list, lang, value, label, sort_order) VALUES
('SUSTAINABILITY', 'es', '1', 'Uso puntual o de aprendizaje; no requiere operación continua', 1),
('SUSTAINABILITY', 'es', '2', 'Uso recurrente, pero aún en evaluación', 2),
('SUSTAINABILITY', 'es', '3', 'Uso continuo; requiere transferencia, apropiación y evolución en el tiempo', 3);