-- **********************************
-- ******** Tables Dashboard ********
-- **********************************

-- Table dashboards
CREATE TABLE dashboards (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name             VARCHAR(100)  NOT NULL,
    description      VARCHAR(500),
    type             VARCHAR(100)   NOT NULL, -- references List_items.value where list='DASHBOARD_TYPE'
    sources_types    VARCHAR(100)   NOT NULL, -- references List_items.value where list='SOURCE_TYPE'
    source_url       TEXT,
    status	         VARCHAR(100)   NOT NULL, -- references List_items.value where list='DASHBOARD_STATUS'
	tags             JSONB,
	detail           TEXT,
    is_active        BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ,
    CONSTRAINT pk_dashboards PRIMARY KEY (id)
);

-- Table parameters
CREATE TABLE parameters (
    dashboard        BIGINT        NOT NULL,
    name             VARCHAR(100)  NOT NULL,
    label            VARCHAR(100)  NOT NULL,
    data_type        VARCHAR(100)  NOT NULL, -- references List_items.value where list='PARAM_TYPE'
    default_value    TEXT,
    is_required      BOOLEAN       NOT NULL DEFAULT FALSE,
    list             VARCHAR(50),
    context_binding  BIGINT,
    is_active        BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ,
    CONSTRAINT pk_parameters PRIMARY KEY (dashboard, name)
);

-- Table favorite_dashboards
CREATE TABLE favorite_dashboards (
    user_id     BIGINT       NOT NULL,
    dashboard   BIGINT       NOT NULL,
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ,
    CONSTRAINT pk_favorite_dashboards PRIMARY KEY (user_id, dashboard)
);

-- Table executions
CREATE TABLE executions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    dashboard      BIGINT        NOT NULL,
    user_id        BIGINT        NOT NULL,
    executed_at    TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    payload        JSONB,
    status         VARCHAR(100), -- references List_items.value where list='EXECUTION_STATUS'
    error_message  TEXT,
    duration_ms    INTEGER,
    CONSTRAINT pk_executions PRIMARY KEY (id)
);

-- Table dashboard_permissions
CREATE TABLE dashboard_permissions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    dashboard     BIGINT        NOT NULL,
    target_type   VARCHAR(100)  NOT NULL, -- references List_items.value where list='TARGET_TYPE'
    target_code   VARCHAR(50)   NOT NULL, -- the recipient identifier
    access_level  VARCHAR(100)  NOT NULL, -- references List_items.value where list='ACCESS_LEVEL'
    valid_from    TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    valid_to      TIMESTAMPTZ,
    CONSTRAINT pk_dashboard_permissions PRIMARY KEY (id)
);

-- ****************************************
-- ************ Foreign Keys **************
-- ****************************************

-- parameters.dashboard → dashboards.id
ALTER TABLE parameters
    ADD CONSTRAINT fk_parameters_dashboards
    FOREIGN KEY (dashboard)
    REFERENCES dashboards (id);

-- parameters.list → lists.code
ALTER TABLE parameters
    ADD CONSTRAINT fk_parameters_lists
    FOREIGN KEY (list)
    REFERENCES lists (code);

-- parameters.context_binding → dashboard_permissions.id
ALTER TABLE parameters
    ADD CONSTRAINT fk_parameters_dashboard_permissions
    FOREIGN KEY (context_binding)
    REFERENCES dashboard_permissions (id);

-- favorite_dashboards.user_id → users.id
ALTER TABLE favorite_dashboards
    ADD CONSTRAINT fk_favorite_dashboards_users
    FOREIGN KEY (user_id)
    REFERENCES users (id);

-- favorite_dashboards.dashboard → dashboards.id
ALTER TABLE favorite_dashboards
    ADD CONSTRAINT fk_favorite_dashboards_dashboards
    FOREIGN KEY (dashboard)
    REFERENCES dashboards (id);

-- dashboard_permissions.dashboard → dashboards.id
ALTER TABLE dashboard_permissions
    ADD CONSTRAINT fk_dashboard_permissions_dashboards
    FOREIGN KEY (dashboard)
    REFERENCES dashboards (id);

-- executions.dashboard → dashboards.id
ALTER TABLE executions
    ADD CONSTRAINT fk_executions_dashboards
    FOREIGN KEY (dashboard)
    REFERENCES dashboards (id);

-- executions.user_id → users.id
ALTER TABLE executions
    ADD CONSTRAINT fk_executions_users
    FOREIGN KEY (user_id)
    REFERENCES users (id);

-- **********************************
-- ***** Table lists/list_items *****
-- **********************************

-- ===== List: Dashboard Type =====
INSERT INTO lists (code, name, description, type, module, is_active) VALUES (
    'DASHBOARD_TYPE', 'List of dashboard types for system configuration',
    'List that classifies the types of dashboards in SynapxIA.',
    'LIST_OF_VALUES', 'ANA', TRUE);
INSERT INTO list_items (list, value, label, sort_order, is_active) VALUES
    ('DASHBOARD_TYPE', 'DASHBOARD', 'Dashboard', 10, TRUE),
    ('DASHBOARD_TYPE', 'REPORT', 'Report', 20, TRUE),
    ('DASHBOARD_TYPE', 'SCORECARD', 'Scorecard', 30, TRUE),
    ('DASHBOARD_TYPE', 'KPI_VIEW', 'KPI View', 40, TRUE),
    ('DASHBOARD_TYPE', 'ANALYTICAL_VIEW', 'Analytical View', 50, TRUE);

-- ===== List: Source Type =====
INSERT INTO lists (code, name, description, type, module, is_active) VALUES (
    'SOURCE_TYPE', 'List of source types for system configuration',
    'List that classifies the types of data sources in SynapxIA.',
    'LIST_OF_VALUES', 'ANA', TRUE);
INSERT INTO list_items (list, value, label, sort_order, is_active) VALUES
    ('SOURCE_TYPE', 'INTERNAL_PAGE', 'Internal Page', 10, TRUE),
    ('SOURCE_TYPE', 'POWER_BI', 'Power BI', 20, TRUE),
    ('SOURCE_TYPE', 'LOOKER_STUDIO', 'Looker Studio', 30, TRUE),
    ('SOURCE_TYPE', 'TABLEAU', 'Tableau', 40, TRUE),
    ('SOURCE_TYPE', 'QLIK_SENSE', 'Qlik Sense', 50, TRUE),
    ('SOURCE_TYPE', 'METABASE', 'Metabase', 60, TRUE),
    ('SOURCE_TYPE', 'SUPERSET', 'Superset', 70, TRUE),
    ('SOURCE_TYPE', 'CUSTOM_IFRAME', 'Custom Iframe', 80, TRUE);

-- ===== List: Dashboard Status =====
INSERT INTO lists (code, name, description, type, module, is_active) VALUES (
    'DASHBOARD_STATUS', 'List of dashboard statuses for system configuration',
    'List that classifies the statuses of dashboards in SynapxIA.',
    'LIST_OF_VALUES', 'ANA', TRUE);
INSERT INTO list_items (list, value, label, sort_order, is_active) VALUES
    ('DASHBOARD_STATUS', 'DRAFT', 'Draft', 10, TRUE),
    ('DASHBOARD_STATUS', 'PUBLISHED', 'Published', 20, TRUE),
    ('DASHBOARD_STATUS', 'ARCHIVED', 'Archived', 30, TRUE),
    ('DASHBOARD_STATUS', 'RETIRED', 'Retired', 40, TRUE);

-- ===== List: Parameter Type =====
INSERT INTO lists (code, name, description, type, module, is_active) VALUES (
    'PARAM_TYPE', 'List of parameter types for system configuration',
    'List that classifies the types of parameters in SynapxIA.',
    'LIST_OF_VALUES', 'ANA', TRUE);
INSERT INTO list_items (list, value, label, sort_order, is_active) VALUES
    ('PARAM_TYPE', 'STRING', 'String', 10, TRUE),
    ('PARAM_TYPE', 'NUMBER', 'Number', 20, TRUE),
    ('PARAM_TYPE', 'BOOLEAN', 'Boolean', 30, TRUE),
    ('PARAM_TYPE', 'DATE', 'Date', 40, TRUE);

-- ===== List: Execution Status =====
INSERT INTO lists (code, name, description, type, module, is_active) VALUES (
    'EXECUTION_STATUS', 'List of execution statuses for dashboard executions',
    'List that classifies the statuses of executions in SynapxIA.',
    'LIST_OF_VALUES', 'ANA', TRUE);
INSERT INTO list_items (list, value, label, sort_order, is_active) VALUES
    ('EXECUTION_STATUS', 'SUCCESS', 'Success', 10, TRUE),
    ('EXECUTION_STATUS', 'FAILED', 'Failed', 20, TRUE),
    ('EXECUTION_STATUS', 'CANCELLED', 'Cancelled', 30, TRUE),
    ('EXECUTION_STATUS', 'TIMEOUT', 'Timeout', 40, TRUE),
    ('EXECUTION_STATUS', 'UNAUTHORIZED', 'Unauthorized', 50, TRUE);