-- **********************************
-- ***** Tables Support *****
-- **********************************

-- Table bug_reports
CREATE TABLE bug_reports (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id       BIGINT        NOT NULL,
    description   TEXT          NOT NULL,
    page_url      TEXT,
    user_agent    TEXT,
    screenshot    TEXT, -- base64 data-URL of the (optionally annotated) screenshot
    attachments   JSONB, -- array of base64 data-URLs (extra images)
    status        VARCHAR(100)  NOT NULL DEFAULT 'OPEN', -- OPEN | RESOLVED
    is_active     BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ,
    CONSTRAINT pk_bug_reports PRIMARY KEY (id),
    CONSTRAINT fk_bug_reports_user FOREIGN KEY (user_id) REFERENCES users(id)
);
