-- **********************************
-- *********** Database *************
-- **********************************
-- create database synapxia;
-- set schema 'synapxia';

-- **********************************
-- ***** Tables Administration ******
-- **********************************

-- Table modules
CREATE TABLE modules (
    code        VARCHAR(50)  NOT NULL,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    sort_order  INT          NOT NULL DEFAULT 0,
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ,
    CONSTRAINT pk_modules PRIMARY KEY (code)
);

-- Table units
CREATE TABLE units (
    code        VARCHAR(50)  NOT NULL,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    type        VARCHAR(100),
    parent      VARCHAR(50),
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ,
    CONSTRAINT pk_units PRIMARY KEY (code)
);

-- Table lists
CREATE TABLE lists (
    code        VARCHAR(50)  NOT NULL,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    module      VARCHAR(50),
    type        VARCHAR(100) NOT NULL,
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ,
    CONSTRAINT pk_lists PRIMARY KEY (code)
);

-- Table list_items
CREATE TABLE list_items (
    list        VARCHAR(50)  NOT NULL,
    value       VARCHAR(100) NOT NULL,
    label       VARCHAR(200) NOT NULL,
    sort_order  INT          NOT NULL DEFAULT 0,
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ,
    CONSTRAINT pk_list_items PRIMARY KEY (list, value)
);

-- Table roles
CREATE TABLE roles (
    code        VARCHAR(50)  NOT NULL,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ,
    CONSTRAINT pk_roles PRIMARY KEY (code)
);

-- Table users
CREATE TABLE users (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username       VARCHAR(50)   NOT NULL UNIQUE,
    email          VARCHAR(100)  NOT NULL UNIQUE,
    password_hash  VARCHAR(500)  NOT NULL,
    first_name     VARCHAR(100)  NOT NULL,
    last_name      VARCHAR(100)  NOT NULL,
    menu_role      VARCHAR(50)   NOT NULL,
    unit           VARCHAR(50)   NOT NULL,
    is_active      BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ,
    last_login_at  TIMESTAMPTZ,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

-- Table options
CREATE TABLE options (
    module      VARCHAR(50)  NOT NULL,
    code        VARCHAR(50)  NOT NULL,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    path        VARCHAR(500),
    icon        VARCHAR(500),
	type        VARCHAR(100) NOT NULL,
    sort_order  INT          NOT NULL DEFAULT 0,
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ,
    CONSTRAINT pk_options PRIMARY KEY (module, code)
);

-- Table privileges
CREATE TABLE privileges (
    role        VARCHAR(50)  NOT NULL,
    module      VARCHAR(50)  NOT NULL,
    option      VARCHAR(50)  NOT NULL,
    can_edit    BOOLEAN      NOT NULL DEFAULT TRUE,
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ,
    CONSTRAINT pk_privileges PRIMARY KEY (role, module, option)
);

-- ****************************************
-- ************ Foreign Keys **************
-- ****************************************

-- lists.module → modules.code
ALTER TABLE lists
    ADD CONSTRAINT fk_lists_modules
    FOREIGN KEY (module)
    REFERENCES modules (code);

-- units.parent_unit → units.code
ALTER TABLE units
    ADD CONSTRAINT fk_units_units
    FOREIGN KEY (parent)
    REFERENCES units (code);

-- list_items.list → lists.code
ALTER TABLE list_items
    ADD CONSTRAINT fk_list_items_lists
    FOREIGN KEY (list)
    REFERENCES lists (code);

-- users.role → roles.code
ALTER TABLE users
    ADD CONSTRAINT fk_users_roles
    FOREIGN KEY (menu_role)
    REFERENCES roles (code);

-- users.unit → units.code
ALTER TABLE users
    ADD CONSTRAINT fk_users_units
    FOREIGN KEY (unit)
    REFERENCES units (code);

-- options.module → modules.code
ALTER TABLE options
    ADD CONSTRAINT fk_options_modules
    FOREIGN KEY (module)
    REFERENCES modules (code);

-- privileges.role → roles.code
ALTER TABLE privileges
    ADD CONSTRAINT fk_privileges_roles
    FOREIGN KEY (role)
    REFERENCES roles (code);

-- privileges.option → options.code
ALTER TABLE privileges
    ADD CONSTRAINT fk_privileges_options
    FOREIGN KEY (module, option)
    REFERENCES options (module, code);

-- **********************************
-- ********* Table: modules *********
-- **********************************

INSERT INTO modules (code, name, description, sort_order) VALUES
    ('ADMIN',
     'Administration',
     'Administration centralizes security, reference data and structural configuration of SynapxIA, ensuring consistent behavior across modules, user profiles and environments.',
     10),
    ('CATALOG',
     'Digital Assets',
     'Digital Assets manages the catalog, characterization and evolution of key digital assets, enabling reuse, governance and alignment with AI initiatives and business needs.',
     20),
    ('COLLAB',
     'Collaboration',
     'Collaboration provides shared spaces, teams and structures so people can coordinate work, track progress and align around AI adoption initiatives across the organization.',
     30),
    ('GEN_AI',
     'Generative AI',
     'Generative AI groups the core GenAI capabilities of SynapxIA, including prompt galleries, MCP integrations, flows, models and agents to design and operate AI-powered solutions.',
     40),
    ('INITS',
     'GenAI Initiatives',
     'AI Initiatives supports the full lifecycle of AI ideas and projects, from proposal and exploration to decision making, tracking and promotion into reusable assets.',
     50),
    ('INSIGHTS',
     'GenAI Insights',
     'GenAI Metrics consolidates KPIs, dashboards and reports that measure the adoption, usage and value of Generative AI across the organization and its processes.',
     60),
    ('WORKFLOWS',
     'Processes',
     'Processes maps the value chain and key process models of the organization, connecting them with AI initiatives, digital assets and GenAI metrics for continuous improvement.',
     70);

-- **********************************
-- ***** Table lists/list_items *****
-- **********************************

-- ===== List: List Type =====
INSERT INTO lists (code, name, description, type, module, is_active) VALUES (
    'LIST_TYPE',
    'List types for system configuration',
    'List that classifies the types of lists in two categories: List of Values and Scale.',
    'LIST_OF_VALUES',
    'ADMIN',
    TRUE);
INSERT INTO list_items (list, value, label, sort_order, is_active) VALUES
    ('LIST_TYPE', 'LIST_OF_VALUES', 'List of Values', 10, TRUE),
    ('LIST_TYPE', 'SCALE', 'Scale', 20, TRUE);

-- ===== List: Option Type =====
INSERT INTO lists (code, name, description, type, module, is_active) VALUES (
    'OPTION_TYPE',
    'Option types for navigation items',
    'List that classifies application options by type, such as content pages, forms or reports.',
    'LIST_OF_VALUES',
    'ADMIN',
     TRUE);
INSERT INTO list_items (list, value, label, sort_order, is_active) VALUES
    ('OPTION_TYPE', 'CONTENT', 'Content', 10, TRUE),
    ('OPTION_TYPE', 'FORM',    'Form',    20, TRUE),
    ('OPTION_TYPE', 'REPORT',  'Report',  30, TRUE);

-- ===== List: Unit Type =====
INSERT INTO lists (code, name, description, type, module, is_active) VALUES (
    'UNIT_TYPE',
    'Types of organizational units',
    'List that classifies the types of organizational units (e.g., Department, Business Unit, Chapter) available in SynapxIA.',
    'LIST_OF_VALUES',
    'ADMIN',
     TRUE);
INSERT INTO list_items (list, value, label, sort_order, is_active) VALUES
    ('UNIT_TYPE', 'BUSINESS_UNIT','Business Unit', 10, TRUE),
    ('UNIT_TYPE', 'DEPARTMENT',   'Department',    20, TRUE),
    ('UNIT_TYPE', 'CHAPTER',      'Chapter',       30, TRUE);
