-- **********************************
-- *********** Database *************
-- **********************************
-- create database synapxia;
-- set schema 'synapxia';

-- **********************************
-- ***** Tables Administration ******
-- **********************************

-- Table modules
CREATE TABLE modules (
    code        VARCHAR(50)  NOT NULL,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    sort_order  INT          NOT NULL DEFAULT 0,
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ,
    CONSTRAINT pk_modules PRIMARY KEY (code)
);

-- Table lists
CREATE TABLE lists (
    code        VARCHAR(50)  NOT NULL,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    module      VARCHAR(50),
    type        VARCHAR(100) NOT NULL,
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ,
    CONSTRAINT pk_lists PRIMARY KEY (code)
);

-- Table list_items
CREATE TABLE list_items (
    list        VARCHAR(50)  NOT NULL,
    value       VARCHAR(100) NOT NULL,
    label       VARCHAR(150) NOT NULL,
    sort_order  INT          NOT NULL DEFAULT 0,
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ,
    CONSTRAINT pk_list_items PRIMARY KEY (list, value)
);

-- Table roles
CREATE TABLE roles (
    code        VARCHAR(50)  NOT NULL,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ,
    CONSTRAINT pk_roles PRIMARY KEY (code)
);

-- Table users
CREATE TABLE users (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username       VARCHAR(50)   NOT NULL UNIQUE,
    email          VARCHAR(100)  NOT NULL UNIQUE,
    password_hash  VARCHAR(255)  NOT NULL,
    first_name     VARCHAR(100)  NOT NULL,
    last_name      VARCHAR(100)  NOT NULL,
    status         VARCHAR(100)  NOT NULL,
    menu_role      VARCHAR(50)   NOT NULL,
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ,
    last_login_at  TIMESTAMPTZ,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

-- Table options
CREATE TABLE options (
    module      VARCHAR(50)  NOT NULL,
    code        VARCHAR(50)  NOT NULL,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    path        VARCHAR(255),
    icon        VARCHAR(100),
	type        VARCHAR(100) NOT NULL,
    sort_order  INT          NOT NULL DEFAULT 0,
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ,
    CONSTRAINT pk_options PRIMARY KEY (module, code)
);

-- Table privileges
CREATE TABLE privileges (
    role        VARCHAR(50)  NOT NULL,
    module      VARCHAR(50)  NOT NULL,
    option      VARCHAR(50)  NOT NULL,
    can_edit    BOOLEAN      NOT NULL DEFAULT TRUE,
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ,
    CONSTRAINT pk_privileges PRIMARY KEY (role, module, option)
);

-- ****************************************
-- ************ Foreign Keys **************
-- ****************************************

-- lists.module → modules.code
ALTER TABLE lists
    ADD CONSTRAINT fk_lists_modules
    FOREIGN KEY (module)
    REFERENCES modules (code);

-- list_items.list → lists.code
ALTER TABLE list_items
    ADD CONSTRAINT fk_list_items_lists
    FOREIGN KEY (list)
    REFERENCES lists (code);

-- users.role → roles.code
ALTER TABLE users
    ADD CONSTRAINT fk_users_roles
    FOREIGN KEY (menu_role)
    REFERENCES roles (code);

-- options.module → modules.code
ALTER TABLE options
    ADD CONSTRAINT fk_options_modules
    FOREIGN KEY (module)
    REFERENCES modules (code);

-- privileges.role → roles.code
ALTER TABLE privileges
    ADD CONSTRAINT fk_privileges_roles
    FOREIGN KEY (role)
    REFERENCES roles (code);

-- privileges.option → options.code
ALTER TABLE privileges
    ADD CONSTRAINT fk_privileges_options
    FOREIGN KEY (module, option)
    REFERENCES options (module, code);
