-- **********************************
-- *********** Database *************
-- **********************************
-- create database synapxia;
-- set schema 'synapxia';

-- **********************************
-- ***** Tables Digital Catalog *****
-- **********************************

-- Table categories
CREATE TABLE categories (
    code        VARCHAR(50)  NOT NULL,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    parent      VARCHAR(50),
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ,
    CONSTRAINT pk_categories PRIMARY KEY (code)
);

-- Table characteristics
CREATE TABLE characteristics (
    code        VARCHAR(50)  NOT NULL,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(500),
	type	    VARCHAR(100)  NOT NULL,
    status	    VARCHAR(100)  NOT NULL,
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ,
    CONSTRAINT pk_characteristics PRIMARY KEY (code)
);

-- Table assets
CREATE TABLE assets (
    code        VARCHAR(50)  NOT NULL,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    category    VARCHAR(50),
    reference   VARCHAR(500),
	type	    VARCHAR(100)  NOT NULL,
    status	    VARCHAR(100)  NOT NULL,
	visibility  VARCHAR(100)  NOT NULL,
	tags        JSON,
	details     JSON,
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ,
    CONSTRAINT pk_assets PRIMARY KEY (code)
);

-- Table characterizations
CREATE TABLE characterizations (
    asset           VARCHAR(50)   NOT NULL,
    characteristic  VARCHAR(50)   NOT NULL,
    value           VARCHAR(500)  NOT NULL,
    details         VARCHAR(500),
    is_active       BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ,
    CONSTRAINT pk_characterizations PRIMARY KEY (asset, characteristic)
);

-- Table favorites
CREATE TABLE favorites (
    user_id     BIGINT       NOT NULL,
    asset       VARCHAR(50)  NOT NULL,
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ,
    CONSTRAINT pk_favorites PRIMARY KEY (user_id, asset)
);

-- Table actions
CREATE TABLE actions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    asset          VARCHAR(50)   NOT NULL,
    user_id        BIGINT        NOT NULL,
	type	       VARCHAR(100)  NOT NULL,
    content        VARCHAR(500),
    reference      VARCHAR(500),
    parent         BIGINT,
	details        JSON,
    is_active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ,
    CONSTRAINT pk_actions PRIMARY KEY (id)
);

-- Table asset_relations
CREATE TABLE asset_relations (
    source      VARCHAR(50)   NOT NULL,
    target      VARCHAR(50)   NOT NULL,
    type        VARCHAR(100)  NOT NULL,
    is_active   BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ,
    CONSTRAINT pk_asset_relations PRIMARY KEY (source, target) 
);

-- ****************************************
-- ************ Foreign Keys **************
-- ****************************************

-- categories.parent → categories.code
ALTER TABLE categories
    ADD CONSTRAINT fk_categories_categories
    FOREIGN KEY (parent)
    REFERENCES categories(code);

-- assets.category → categories.code
ALTER TABLE assets
    ADD CONSTRAINT fk_assets_categories
    FOREIGN KEY (category)
    REFERENCES categories(code);

-- characterizations.asset → assets.code
ALTER TABLE characterizations
    ADD CONSTRAINT fk_characterizations_assets
    FOREIGN KEY (asset)
    REFERENCES assets (code);

-- characterizations.characteristic → characteristics.code
ALTER TABLE characterizations
    ADD CONSTRAINT fk_characterizations_characteristics
    FOREIGN KEY (characteristic)
    REFERENCES characteristics (code);

-- favorites.user_id → users.id
ALTER TABLE favorites
    ADD CONSTRAINT fk_favorites_users
    FOREIGN KEY (user_id)
    REFERENCES users (id);

-- favorites.asset → assets.code
ALTER TABLE favorites
    ADD CONSTRAINT fk_favorites_assets
    FOREIGN KEY (asset)
    REFERENCES assets (code);

-- actions.asset → assets.code
ALTER TABLE actions 
    ADD CONSTRAINT fk_actions_assets
    FOREIGN KEY (asset)
    REFERENCES assets (code);

-- actions.user_id → users.id
ALTER TABLE actions
    ADD CONSTRAINT fk_actions_users
    FOREIGN KEY (user_id)
    REFERENCES users (id);

-- actions.parent → actions.id
ALTER TABLE actions
    ADD CONSTRAINT fk_actions_actions
    FOREIGN KEY (parent)
    REFERENCES actions(id);

-- asset_relations.source → assets.code
ALTER TABLE asset_relations 
    ADD CONSTRAINT fk_asset_relations_source_assets
    FOREIGN KEY (source)
    REFERENCES assets (code);

-- asset_relations.target → assets.code
ALTER TABLE asset_relations 
    ADD CONSTRAINT fk_asset_relations_target_assets
    FOREIGN KEY (target)
    REFERENCES assets (code);

-- **********************************
-- ***** Table lists/list_items *****
-- **********************************

-- ===== List: Characteristic Type =====
INSERT INTO lists (code, name, description, type, module, is_active) VALUES (
    'CHARS_TYPE',
    'List characteristics for system configuration',
    'List that classifies the types of characteristics (e.g., General, Technical, Commercial, Usability, Documentation and Platform) available in SynapxIA.',
    'LIST_OF_VALUES',
    'CATALOG',
    TRUE);
INSERT INTO list_items (list, value, label, sort_order, is_active) VALUES
    ('CHARS_TYPE', 'GENERAL', 'General', 10, TRUE),
    ('CHARS_TYPE', 'TECHNICAL', 'Technical', 20, TRUE),
    ('CHARS_TYPE', 'COMMERCIAL', 'Commercial', 30, TRUE),
    ('CHARS_TYPE', 'USABILITY', 'Usability', 40, TRUE),
    ('CHARS_TYPE', 'DOCUMENTATION', 'Documentation', 50, TRUE),
    ('CHARS_TYPE', 'PLATFORM', 'Platform', 60, TRUE);

-- ===== List: Asset Visibility =====
INSERT INTO lists (code, name, description, type, module, is_active) VALUES (
    'ASSET_VISIBILITY',
    'List asset visibility for system configuration',
    'List that classifies the visibility of assets in SynapxIA (e.g., Public, Private, Internal).',
    'LIST_OF_VALUES',
    'CATALOG',
    TRUE);
INSERT INTO list_items (list, value, label, sort_order, is_active) VALUES
    ('ASSET_VISIBILITY', 'PUBLIC', 'Public', 10, TRUE),
    ('ASSET_VISIBILITY', 'PRIVATE', 'Private', 20, TRUE),
    ('ASSET_VISIBILITY', 'INTERNAL', 'Internal', 30, TRUE);

-- ===== List: Asset Status =====
INSERT INTO lists (code, name, description, type, module, is_active) VALUES (
    'ASSET_STATUS',
    'List asset statuses for system configuration',
    'List that classifies the statuses of assets in SynapxIA (e.g., Created, Proposed, Feedback Provided, Published, Rejected).',
    'LIST_OF_VALUES',
    'CATALOG',
    TRUE);
INSERT INTO list_items (list, value, label, sort_order, is_active) VALUES
    ('ASSET_STATUS', 'CREATED', 'Created', 10, TRUE),
    ('ASSET_STATUS', 'PROPOSED', 'Proposed', 20, TRUE),
    ('ASSET_STATUS', 'FEEDBACK', 'Feedback Provided', 30, TRUE),
    ('ASSET_STATUS', 'PUBLISHED', 'Published', 40, TRUE),
    ('ASSET_STATUS', 'REJECTED', 'Rejected', 50, TRUE);

-- ===== List: Action Type =====
INSERT INTO lists (code, name, description, type, module, is_active) VALUES (
    'ACTION_TYPE',
    'List action types for system configuration',
    'List that classifies the types of actions that users can perform on assets in SynapxIA (e.g., Proposal, Review, Modification, Publication, Rejection, Deprecation, Vote).',
    'LIST_OF_VALUES',
    'CATALOG',
    TRUE);
INSERT INTO list_items (list, value, label, sort_order, is_active) VALUES
    ('ACTION_TYPE', 'PROPOSAL', 'Proposal', 10, TRUE),
    ('ACTION_TYPE', 'REVIEW', 'Review', 20, TRUE),
    ('ACTION_TYPE', 'MODIFICATION', 'Modification', 30, TRUE),
    ('ACTION_TYPE', 'PUBLICATION', 'Publication', 40, TRUE),
    ('ACTION_TYPE', 'REJECTION', 'Rejection', 50, TRUE),
    ('ACTION_TYPE', 'DEPRECATION', 'Deprecation', 60, TRUE),
    ('ACTION_TYPE', 'USAGE', 'Usage', 70, TRUE),
    ('ACTION_TYPE', 'VOTE', 'Vote', 80, TRUE),
    ('ACTION_TYPE', 'COMMENT', 'Comment', 90, TRUE),
    ('ACTION_TYPE', 'QUESTION', 'Question', 100, TRUE),
    ('ACTION_TYPE', 'ANSWER', 'Answer', 110, TRUE),
    ('ACTION_TYPE', 'REQUEST', 'Request', 120, TRUE);

-- ===== List: Asset Relation Type =====
INSERT INTO lists (code, name, description, type, module, is_active) VALUES (
    'ASSET_REL_TYPE',
    'List asset relation types for system configuration',
    'List that classifies the types of relationships between assets in SynapxIA (e.g., Depends On, Related To, Similar To, Alternative To).',
    'LIST_OF_VALUES',
    'CATALOG',
    TRUE);
INSERT INTO list_items (list, value, label, sort_order, is_active) VALUES
    ('ASSET_REL_TYPE', 'DEPENDS_ON', 'Depends On', 10, TRUE),
    ('ASSET_REL_TYPE', 'RELATED_TO', 'Related To', 20, TRUE),
    ('ASSET_REL_TYPE', 'SIMILAR_TO', 'Similar To', 30, TRUE),
    ('ASSET_REL_TYPE', 'ALTERNATIVE_TO', 'Alternative To', 40, TRUE);
